// GENERATED — tool/build_pose_sheets.py 로 재생성. 손으로 고치지 말 것.
// tool/character/ 포즈시트를 assets/pets/ 로 복사한 결과의 키 집합.

const Set<String> poseSheetKeys = {
  'bear_2',
  'bear_3',
  'bear_4',
  'bird_2',
  'bird_3',
  'bird_4',
  'gumiho_2',
  'gumiho_3',
  'gumiho_4',
  'haetae_2',
  'haetae_3',
  'haetae_4',
  'moonrabbit_2',
  'moonrabbit_3',
  'moonrabbit_4',
  'samjoko_2',
  'samjoko_3',
  'samjoko_4',
  'snake_2',
  'snake_3',
  'snake_4',
  'tiger_2',
  'tiger_3',
  'tiger_4',
  'toad_2',
  'toad_3',
  'turtle_2',
  'turtle_3',
  'turtle_4',
};
